spring:
<<<<<<< HEAD
  application:
    name: mamoki

  jpa:
    hibernate:
      ddl-auto: validate # Entity랑 테이블 구조 일치하는지만 확인 -> 운영 환경에서 안전한 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  forward-headers-strategy: native # X-Forwarded-For 헤더를 읽어 실제 클라이언트 IP 인식 가능 -> 배포 환경에서 필요한 설정

logging:
  level:
    root: info
    com.mamoki: DEBUG

custom:
  jwt:
    secret-key: ${JWT_SECRET}
    access-exp-min: ${JWT_ACCESS_EXP_MIN:60} # 토큰 유효시간 : 60분
    refresh-exp-day: ${JWT_REFRESH_EXP_DAY:30} # RT 유효시간 : 30일
=======
  profiles:
    active: local
>>>>>>> 0f39ac69dfdec742e6bd6e3615fff602bf96b77a
