spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  jwt:
    secret-key: ${JWT_SECRET}
    access-exp-min: ${JWT_ACCESS_EXP_MIN}
    refresh-exp-day: ${JWT_REFRESH_EXP_DAY}

firebase:
  beacon-account:
    path: firebase/beacon-account.json